name: 'publish'

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install -g pnpm && pnpm install

      - name: Get commit messages since last release
        id: get-changes
        shell: bash
        run: |
          # Fetch all existing tags
          git fetch --tags -f
          
          # Get previous tag (last release)
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # No previous tag found - get all commits
            CHANGES=$(git log --pretty=format:"- %s")
          else
            # Get commits between previous tag and current HEAD
            CHANGES=$(git log --pretty=format:"- %s" "$PREVIOUS_TAG..HEAD")
          fi
          
          # Add to environment variables (with proper multiline handling)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGES<<$EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: |
            ## Whats new
            ${{ env.CHANGES }}

            ### Installation
            See the assets below to download this version.
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true